theme = "gruvbox"

[editor]
line-number  = "relative"
auto-pairs   = true
auto-save    = true
bufferline   = "always"
completion-timeout = 90
true-color   = true
color-modes  = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
git-ignore = true
hidden = false
ignore = true

[editor.indent-guides]
character = "╎"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.whitespace]
[editor.whitespace.characters]
newline = "⌄"

[editor.whitespace.render]
newline = "all"

[keys]
[keys.normal]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["open_below", "normal_mode"]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
