[[language]]
language-servers = ["ts"]
name = "javascript"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["ts"]
name = "typescript"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["ts"]
name = "tsx"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["html", "emmet"]
name = "html"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["json"]
name = "json"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["css"]
name = "css"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
language-servers = ["css"]
name = "scss"
auto-format = true
formatter = { command = "prettierd", args = ["--stdin-filepath", "{}"] }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixfmt" }

[language-server]
[language-server.tailwind]
args = ["--stdio"]
command = "tailwindcss-language-server"

[language-server.emmet]
args = ["--stdio"]
command = "emmet-ls"

[language-server.css]
args = ["--stdio"]
command = "/nix/store/d30vpvgbn7l5kmx28cj9abm0nlcnmbm7-vscode-langservers-extracted-4.8.0/bin/vscode-css-language-server"

[language-server.html]
args = ["--stdio"]
command = "/nix/store/d30vpvgbn7l5kmx28cj9abm0nlcnmbm7-vscode-langservers-extracted-4.8.0/bin/vscode-html-language-server"

[language-server.json]
args = ["--stdio"]
command = "/nix/store/d30vpvgbn7l5kmx28cj9abm0nlcnmbm7-vscode-langservers-extracted-4.8.0/bin/vscode-json-language-server"

[language-server.ts]
args = ["--stdio"]
command = "/nix/store/jqrnx000b5navgsf111b9ivciz8jcqzz-typescript-language-server-4.1.0/bin/typescript-language-server"
