theme = "fleet_dark"

[editor]
true-color   = true
auto-pairs   = true
auto-save    = true
idle-timeout = 50

[editor.indent-guides]
render    = true
character = "╎"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"

[editor.file-picker] 
hidden     = false
git-ignore = true
ignore     = true

[keys.normal]
"}"   = "goto_next_paragraph"
"{"   = "goto_prev_paragraph"
"d"   = "delete_selection_noyank"
"A-d" = "delete_selection"
"c"   = "change_selection_noyank"
"A-c" = "change_selection"
"ret" = ["open_below", "normal_mode"]

[keys.select]
"}"   = "goto_next_paragraph"
"{"   = "goto_prev_paragraph"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "⌄"