theme = "fleet_dark"

[editor]
line-number  = "relative"
true-color   = true
auto-pairs   = true
auto-save    = true
idle-timeout = 50

[editor.indent-guides]
render    = true
character = "╎"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"}"   = "goto_next_paragraph"
"{"   = "goto_prev_paragraph"
"d"   = "delete_selection_noyank"
"A-d" = "no_op"
"c"   = "change_selection_noyank"
"A-c" = "no_op"
"ret" = ["open_below", "normal_mode"]

[keys.select]
"}"   = "goto_next_paragraph"
"{"   = "goto_prev_paragraph"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "⌄"