[[language]]
name = "rust"

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.config.check]
command = "clippy"


[[language]]
name = "typescript"
indent = { tab-width = 4, unit = " " }

[language.language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = " " }

[language.language-server]
command = "npx"
args = ["typescript-language-server", "--stdio"]

