[[language]]
name = "rust"

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.config.check]
command = "clippy"

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = " " }

