[[language]]
name = "rust"

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.config.check]
command = "clippy"

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "scss"
formatter = { command = 'prettier', args = ["--parser", "scss"] }
